# This pipeline is used to release a set of packages into respective environments
# Changelog will be written to changelog branch

name: "CD Pipeline - User Triggered"

on:
  workflow_dispatch:
    inputs:
      pathToReleaseDef:
        description: "Path to release definition file"
        required: true

jobs:
  UAT:
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    environment:
      name: UAT
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Authenticate to UAT sandbox
        run: |
          echo "${{ secrets.UAT_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f ./authfile -a st

      # Authenticate to npm
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"

      # Release to environment
      - name: "Release to UAT"
        run: 'sfdx sfpowerscripts:orchestrator:release -u st -p ${{ github.event.inputs.pathToReleaseDef }} --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname changelog -g "::group::,::endgroup::"'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  PROD:
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    if: github.ref == 'refs/heads/master' || contains(github.ref,'refs/heads/release')
    environment:
      name: PROD
    needs: UAT

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Authenticate to PROD
        run: |
          echo "${{ secrets.PROD_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f ./authfile -a prod

      # Authenticate to npm
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"

      # Release to environment
      - name: "Release to PROD"
        run: 'sfdx sfpowerscripts:orchestrator:release -u prod -p ${{ github.event.inputs.pathToReleaseDef }} --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname changelog -g "::group::,::endgroup::"'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
