# This pipeline is used to validate an incoming change using a dev environment fetched from the CI pool

name: "PR Validation - Auto Triggered"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - release/**
    # Specifing the force-app the directory that is relevant for the check
    paths:
      - force-app/**
      - data/**
      - src-env-specific/**

jobs:
  validate:
    name: "Validate Changed Packages"
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Authenticate Dev Hub"
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub

      # Validate source and trigger test
      - name: "Push source to scratch org"
        run: "sfdx sfpowerscripts:orchestrator:validate -p ci -v devhub -x"

  static:
    name: "Static analysis of Apex Classes using PMD"
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Run PMD static code analysis"
        shell: bash
        run: |
          sfdx sfpowerscripts:analyze:pmd -b --sourcedir=force-app -o force-app-pmd-output

  validate-package-coverage:
    name: "validate metadata coverage for unlocked packages"
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "validate metadata coverage"
        shell: bash
        run: |
          sfdx sfpowerkit:package:valid -n force-app -b StandardValueSet
